version: 2
jobs:
  build:
    working_directory: ~/php-swaggerize-fastroute-library
    docker:
      - image: circleci/php:5.5
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: composer install && ./vendor/bin/phpcs --config-set installed_paths $PWD/vendor/escapestudios/symfony2-coding-standard,$PWD/vendor/iadvize/php-convention/phpcs >> /dev/null
      - run:
          name: Run phpunit
          command: phpunit --configuration tests/phpunit.xml
      - run:
          name: Run phpcs
          command: ./vendor/bin/phpcs --standard=Iadvize src
      - run:
          name: Run phpmd
          commadn: ./vendor/bin/phpmd src text vendor/iadvize/php-convention/phpmd/phpmd.xml
